@startuml Bundle
class Bundle {
    -name: str
    -v: float
    -num_conductors: int
    -spacing: float
    -conductor: Conductor

    +verify_num(): void
    +calc_DSC(): float
    +calc_DSL(): float
}
@enduml

@startuml Bus
class Bus {
    -name: str
    -base_kv: float
    -index: int
    +Vpu: float
    +V: float
    +angle: float
    +real_power: float
    +reactive_power: float
    +type: str

    +set_bus_v(v: float): void
    +set_angle(a: float): void
    +set_type(t: str): void
    +set_power(real: float, reactive: float): void
}
@enduml


@startuml Load
class Load {
    -name: str
    -bus: str
    -real_power: float
    -reactive_power: float
    +Smag: float
    +S: float
    +pf: float
    +angle: float
}
@enduml


@startuml Generator
class Generator {
    -name: str
    -bus: str
    -voltage: float
    -real_power: float
    -sub_transient_reactance: 0.0
    -neg_impedance: 0.0
    -zero_impedance: 0.0
    -gnd_impedance: None
    +reactive_power: float
    +Yprim0: np.array

    +set_power(real: float, reactive: float): void
    +calc_Y0prim(): np.array
}
@enduml


@startuml Circuit
class Circuit {
    -name: str
    +powerbase: float
    +count: int
    +i: Dict{str: float}
    +table: list[str]
    +components: dict{str: Component}
    +buses: {str: Bus}
    +conductors: {str: Conductor}
    +bundles: {str: Bundle}
    +geometries: {str: Geometry}

    +add_bus(name: str, voltage: float): void
    +add_resistor(name: str, r: float, bus1: str, bus2: str): void
    +add_load(name: str, power: float, reactive: float, voltage: float, bus: str): void
    +add_voltage_source(name: str, v: float, bus: str): void
    +add_tline_from_geometry(name: str, bus1: Bus, bus2: Bus, bundle: Bundle, geometry: Geometry, length: float)
    +add_tline_from_parameters(name: str, bus1: Bus, bus2: Bus, R: float, X: float, B: float)
    +add_transformer(name: str, bus1: Bus, bus2: Bus, power_rating: float, impedance_percent: float, 
                    x_over_r_ratio: float)
    +add_conductor(name: str, diam: float, GMR: float, resistance: float, ampacity: float)
    +add_bundle(name: str, num_conductors: int, spacing: float, conductor: Conductor)
    +add_geometry(name: str, x: list[float], y: list[float])
    +calc_Ybus(): DataFrame
    +check_bus_names(index: int, name: str): void
}
@enduml

@startuml Conductor
class Conductor {
    -name: str
    -diam: float
    -radius: float
    -GMR: float
    -resistance: float
    -ampacity: float
}
@enduml

@startuml Geometry
class Geometry {
    -name: str
    -x: list[float]
    -y: list[float]
    +Deq: float

    +calc_Deq(): float
}
@enduml

@startuml Settings
class Settings {
    -freq: float
    -powerbase: float

    +set_freq(float): void
    +set_powerbase(float): void
}
@enduml

@startuml Solution
class Solution {
    +circuit: Circuit
}
@enduml

@startuml Transformer
class Transformer {
    -name: str
    -bus1: Bus
    -bus2: Bus
    -power_rating: float
    -impedance_percent: float
    -x_over_r_ratio: float
    +Zpu: float
    +Ypu: float
    +yprim: DataFrame

    +calc_impedance(): complex
    +calc_admittance(): complex
    +calc_yprim(): DataFrame
}
@enduml

@startuml TransmissionLine
class TransmissionLine {
    -name: str
    -bus1: Bus
    -bus2: Bus
    -bundle: Bundle
    -geometry: Geometry
    -length: float
    +freq: float
    +powerbase: float
    +Zbase: float
    +R: float
    +X: float
    +Zseries: complex
    +Yseries: complex
    +Yshunt: complex
    +yprim: DataFrame

    +calc_R(): float
    +calc_X(): float
    +calc_B(): float
    +calc_yprim(): DataFrame
}
@enduml